[2023-11-13T04:06:58.945+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:06:58.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:06:58.951+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:06:58.950+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:07:00.641+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:07:01.002+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:01.001+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-13T04:07:01.144+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:01.144+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-13T04:07:01.267+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:01.266+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-13T04:07:01.268+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:01.268+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:07:01.304+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:01.303+0000] {dag.py:2963} INFO - Creating ORM DAG for ETL_FinancialReport
[2023-11-13T04:07:01.331+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:01.331+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:07:01.504+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 2.563 seconds
[2023-11-13T04:07:31.989+0000] {processor.py:157} INFO - Started process (PID=264) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:07:31.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:07:31.993+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:31.993+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:07:32.481+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:07:32.770+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:32.769+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:07:32.944+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:07:32.943+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:07:34.782+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 2.796 seconds
[2023-11-13T04:08:06.379+0000] {processor.py:157} INFO - Started process (PID=277) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:08:06.381+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:08:06.383+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:08:06.382+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:08:06.936+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:08:07.285+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:08:07.284+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:08:07.333+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:08:07.333+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:08:07.687+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.312 seconds
[2023-11-13T04:08:38.038+0000] {processor.py:157} INFO - Started process (PID=284) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:08:38.039+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:08:38.041+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:08:38.041+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:08:38.571+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:08:38.816+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:08:38.815+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:08:38.862+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:08:38.862+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:08:39.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.020 seconds
[2023-11-13T04:09:09.576+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:09:09.578+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:09:09.580+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:09:09.579+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:09:10.285+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:09:10.335+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:09:10.335+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:09:10.376+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:09:10.376+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:09:10.585+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.012 seconds
[2023-11-13T04:09:41.448+0000] {processor.py:157} INFO - Started process (PID=298) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:09:41.450+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:09:41.452+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:09:41.451+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:09:42.129+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:09:42.185+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:09:42.184+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:09:42.231+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:09:42.231+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:09:42.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.981 seconds
[2023-11-13T04:10:13.342+0000] {processor.py:157} INFO - Started process (PID=305) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:10:13.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:10:13.346+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:10:13.345+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:10:14.042+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:10:14.095+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:10:14.095+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:10:14.141+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:10:14.141+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:10:14.363+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.025 seconds
[2023-11-13T04:10:44.818+0000] {processor.py:157} INFO - Started process (PID=312) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:10:44.819+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:10:44.821+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:10:44.821+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:10:45.524+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:10:45.576+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:10:45.575+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:10:45.631+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:10:45.631+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:10:45.833+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.020 seconds
[2023-11-13T04:11:16.542+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:11:16.544+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:11:16.545+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:11:16.545+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:11:17.275+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:11:17.329+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:11:17.329+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:11:17.374+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:11:17.373+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:11:17.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.039 seconds
[2023-11-13T04:11:48.626+0000] {processor.py:157} INFO - Started process (PID=327) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:11:48.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:11:48.630+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:11:48.629+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:11:49.347+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:11:49.415+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:11:49.414+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:11:49.470+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:11:49.470+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:11:49.661+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.040 seconds
[2023-11-13T04:12:23.256+0000] {processor.py:157} INFO - Started process (PID=394) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:12:23.258+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:12:23.260+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:12:23.260+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:12:23.939+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:12:23.993+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:12:23.993+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:12:24.039+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:12:24.039+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:12:24.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.059 seconds
[2023-11-13T04:13:13.232+0000] {processor.py:157} INFO - Started process (PID=455) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:13:13.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:13:13.238+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:13:13.237+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:13:14.011+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:13:14.059+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:13:14.058+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:13:14.106+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:13:14.106+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:13:14.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.074 seconds
[2023-11-13T04:13:46.659+0000] {processor.py:157} INFO - Started process (PID=521) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:13:46.661+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:13:46.663+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:13:46.663+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:13:47.495+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:13:47.548+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:13:47.547+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:13:47.594+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:13:47.593+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:13:48.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.561 seconds
[2023-11-13T04:14:19.534+0000] {processor.py:157} INFO - Started process (PID=528) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:14:19.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:14:19.538+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:14:19.538+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:14:20.294+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:14:20.343+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:14:20.342+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:14:20.385+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:14:20.384+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:14:20.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.424 seconds
[2023-11-13T04:14:52.218+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:14:52.220+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:14:52.222+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:14:52.221+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:14:52.964+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:14:53.013+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:14:53.012+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:14:53.056+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:14:53.056+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:14:53.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.047 seconds
[2023-11-13T04:15:23.568+0000] {processor.py:157} INFO - Started process (PID=542) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:15:23.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:15:23.573+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:15:23.572+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:15:24.232+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:15:24.287+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:15:24.287+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:15:24.333+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:15:24.332+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:15:24.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.360 seconds
[2023-11-13T04:15:56.010+0000] {processor.py:157} INFO - Started process (PID=549) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:15:56.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:15:56.014+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:15:56.013+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:15:56.723+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:15:56.785+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:15:56.784+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:15:56.832+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:15:56.832+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:15:57.505+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.499 seconds
[2023-11-13T04:16:01.883+0000] {processor.py:157} INFO - Started process (PID=551) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:01.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:16:01.886+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:01.886+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:02.690+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:02.747+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:02.747+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:16:02.794+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:02.794+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:16:03.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.575 seconds
[2023-11-13T04:16:14.967+0000] {processor.py:157} INFO - Started process (PID=557) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:14.968+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:16:14.970+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:14.970+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:15.937+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:15.919+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 32, in LoadBCTC
    cursor.execute('''
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 12 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[2023-11-13T04:16:15.945+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:16.743+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.780 seconds
[2023-11-13T04:16:22.308+0000] {processor.py:157} INFO - Started process (PID=560) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:22.310+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:16:22.311+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:22.311+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:23.428+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:23.410+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 32, in LoadBCTC
    cursor.execute('''
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 12 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[2023-11-13T04:16:23.437+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:23.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.522 seconds
[2023-11-13T04:16:26.207+0000] {processor.py:157} INFO - Started process (PID=562) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:26.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:16:26.211+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:26.211+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:27.228+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:27.206+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 32, in LoadBCTC
    cursor.execute('''
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 12 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[2023-11-13T04:16:27.241+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:27.756+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.554 seconds
[2023-11-13T04:16:58.233+0000] {processor.py:157} INFO - Started process (PID=569) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:58.236+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:16:58.240+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:58.239+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:59.202+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:16:59.186+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 32, in LoadBCTC
    cursor.execute('''
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 12 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[2023-11-13T04:16:59.210+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:16:59.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.271 seconds
[2023-11-13T04:17:03.804+0000] {processor.py:157} INFO - Started process (PID=571) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:03.807+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:17:03.809+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:03.808+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:04.658+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:04.641+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:\DataEngineerirflowirflow\exampledataBCTC.json does not exist
[2023-11-13T04:17:04.660+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:04.768+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.968 seconds
[2023-11-13T04:17:06.308+0000] {processor.py:157} INFO - Started process (PID=573) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:06.310+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:17:06.312+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:06.311+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:07.147+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:07.128+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:\DataEngineerirflowirflow\example/dataBCTC.json does not exist
[2023-11-13T04:17:07.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:07.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.956 seconds
[2023-11-13T04:17:10.242+0000] {processor.py:157} INFO - Started process (PID=575) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:10.244+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:17:10.246+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:10.245+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:11.066+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:11.046+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:\DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:17:11.069+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:11.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.056 seconds
[2023-11-13T04:17:12.760+0000] {processor.py:157} INFO - Started process (PID=577) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:12.762+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:17:12.764+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:12.763+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:13.592+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:13.574+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:17:13.596+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:13.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.979 seconds
[2023-11-13T04:17:31.418+0000] {processor.py:157} INFO - Started process (PID=584) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:31.420+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:17:31.422+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:31.421+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:32.209+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:32.194+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:17:32.212+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:32.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.913 seconds
[2023-11-13T04:17:36.774+0000] {processor.py:157} INFO - Started process (PID=586) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:36.776+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:17:36.778+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:36.777+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:37.580+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:17:37.565+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:17:37.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:17:37.710+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.941 seconds
[2023-11-13T04:18:08.308+0000] {processor.py:157} INFO - Started process (PID=593) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:08.310+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:18:08.312+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:18:08.312+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:09.227+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:18:09.210+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:18:09.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:09.336+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.032 seconds
[2023-11-13T04:18:30.655+0000] {processor.py:157} INFO - Started process (PID=600) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:30.657+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:18:30.659+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:18:30.658+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:31.518+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:18:31.501+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:18:31.522+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:31.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.985 seconds
[2023-11-13T04:18:40.140+0000] {processor.py:157} INFO - Started process (PID=602) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:40.142+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:18:40.145+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:18:40.144+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:40.992+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:18:40.977+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:18:40.994+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:18:41.101+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.966 seconds
[2023-11-13T04:19:03.211+0000] {processor.py:157} INFO - Started process (PID=609) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:03.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:19:03.215+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:19:03.214+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:04.005+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:19:03.987+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:19:04.008+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:04.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.911 seconds
[2023-11-13T04:19:05.455+0000] {processor.py:157} INFO - Started process (PID=611) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:05.458+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:19:05.461+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:19:05.460+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:06.294+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:19:06.274+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:19:06.296+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:06.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.959 seconds
[2023-11-13T04:19:37.657+0000] {processor.py:157} INFO - Started process (PID=618) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:37.659+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:19:37.661+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:19:37.660+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:38.348+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:19:38.334+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:19:38.350+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:38.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.795 seconds
[2023-11-13T04:19:46.926+0000] {processor.py:157} INFO - Started process (PID=620) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:46.928+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:19:46.929+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:19:46.929+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:47.683+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:19:47.665+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:19:47.685+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:19:47.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.885 seconds
[2023-11-13T04:20:18.773+0000] {processor.py:157} INFO - Started process (PID=627) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:20:18.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:20:18.777+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:20:18.777+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:20:19.555+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:20:19.537+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:20:19.558+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:20:19.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.927 seconds
[2023-11-13T04:20:50.574+0000] {processor.py:157} INFO - Started process (PID=634) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:20:50.576+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:20:50.578+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:20:50.578+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:20:51.274+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:20:51.257+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:20:51.276+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:20:51.391+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.822 seconds
[2023-11-13T04:21:22.377+0000] {processor.py:157} INFO - Started process (PID=641) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:21:22.378+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:21:22.380+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:21:22.380+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:21:23.096+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:21:23.079+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:21:23.099+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:21:23.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.893 seconds
[2023-11-13T04:21:54.368+0000] {processor.py:157} INFO - Started process (PID=648) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:21:54.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:21:54.372+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:21:54.371+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:21:55.053+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:21:55.035+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:21:55.056+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:21:55.173+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.809 seconds
[2023-11-13T04:22:09.544+0000] {processor.py:157} INFO - Started process (PID=655) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:09.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:22:09.548+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:22:09.547+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:10.335+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:22:10.320+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 272, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:22:10.338+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:10.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.953 seconds
[2023-11-13T04:22:11.835+0000] {processor.py:157} INFO - Started process (PID=657) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:11.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:22:11.839+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:22:11.838+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:12.615+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:22:12.597+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:22:12.617+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:12.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.902 seconds
[2023-11-13T04:22:43.065+0000] {processor.py:157} INFO - Started process (PID=664) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:43.067+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:22:43.069+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:22:43.069+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:43.859+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:22:43.840+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:22:43.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:22:43.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.933 seconds
[2023-11-13T04:23:14.931+0000] {processor.py:157} INFO - Started process (PID=671) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:14.933+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:23:14.935+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:23:14.934+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:15.715+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:23:15.698+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:23:15.718+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:15.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.904 seconds
[2023-11-13T04:23:19.071+0000] {processor.py:157} INFO - Started process (PID=673) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:19.073+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:23:19.075+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:23:19.074+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:19.942+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:23:19.923+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:23:19.944+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:20.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.981 seconds
[2023-11-13T04:23:50.684+0000] {processor.py:157} INFO - Started process (PID=680) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:50.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:23:50.687+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:23:50.687+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:51.440+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:23:51.423+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:23:51.443+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:23:51.557+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.877 seconds
[2023-11-13T04:24:22.964+0000] {processor.py:157} INFO - Started process (PID=687) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:24:22.966+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:24:22.968+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:24:22.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:24:23.653+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:24:23.634+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:24:23.655+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:24:23.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.803 seconds
[2023-11-13T04:24:54.321+0000] {processor.py:157} INFO - Started process (PID=694) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:24:54.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:24:54.325+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:24:54.324+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:24:55.036+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:24:55.018+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:24:55.038+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:24:55.162+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.845 seconds
[2023-11-13T04:25:25.818+0000] {processor.py:157} INFO - Started process (PID=701) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:25:25.819+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:25:25.821+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:25:25.821+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:25:26.601+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:25:26.588+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:25:26.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:25:26.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.895 seconds
[2023-11-13T04:25:57.775+0000] {processor.py:157} INFO - Started process (PID=708) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:25:57.777+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:25:57.779+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:25:57.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:25:58.573+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:25:58.560+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:25:58.576+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:25:58.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.903 seconds
[2023-11-13T04:26:29.601+0000] {processor.py:157} INFO - Started process (PID=715) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:26:29.603+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:26:29.605+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:26:29.604+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:26:30.311+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:26:30.294+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 270, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:26:30.313+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:26:30.424+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.827 seconds
[2023-11-13T04:26:59.743+0000] {processor.py:157} INFO - Started process (PID=722) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:26:59.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:26:59.747+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:26:59.747+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:27:00.580+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:27:00.565+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:27:00.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:27:00.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.960 seconds
[2023-11-13T04:27:31.107+0000] {processor.py:157} INFO - Started process (PID=729) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:27:31.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:27:31.111+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:27:31.111+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:27:31.851+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:27:31.837+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:27:31.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:27:31.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.848 seconds
[2023-11-13T04:28:02.244+0000] {processor.py:157} INFO - Started process (PID=736) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:28:02.246+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:28:02.248+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:28:02.247+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:28:03.079+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:28:03.060+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:28:03.083+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:28:03.184+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.944 seconds
[2023-11-13T04:28:33.474+0000] {processor.py:157} INFO - Started process (PID=743) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:28:33.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:28:33.478+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:28:33.478+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:28:34.215+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:28:34.195+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:28:34.217+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:28:34.456+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.986 seconds
[2023-11-13T04:29:05.460+0000] {processor.py:157} INFO - Started process (PID=750) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:29:05.463+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:29:05.464+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:29:05.464+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:29:06.199+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:29:06.183+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:29:06.201+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:29:06.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.848 seconds
[2023-11-13T04:29:36.501+0000] {processor.py:157} INFO - Started process (PID=757) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:29:36.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:29:36.505+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:29:36.505+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:29:37.231+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:29:37.211+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:29:37.234+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:29:37.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.854 seconds
[2023-11-13T04:30:08.225+0000] {processor.py:157} INFO - Started process (PID=764) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:30:08.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:30:08.229+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:30:08.229+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:30:09.042+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:30:09.025+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:30:09.045+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:30:09.168+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.947 seconds
[2023-11-13T04:30:40.014+0000] {processor.py:157} INFO - Started process (PID=771) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:30:40.016+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:30:40.019+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:30:40.018+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:30:40.712+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:30:40.699+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:30:40.715+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:30:40.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.817 seconds
[2023-11-13T04:31:11.281+0000] {processor.py:157} INFO - Started process (PID=778) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:31:11.283+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:31:11.285+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:31:11.284+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:31:12.006+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:31:11.989+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:31:12.009+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:31:12.116+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.839 seconds
[2023-11-13T04:31:42.930+0000] {processor.py:157} INFO - Started process (PID=785) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:31:42.931+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:31:42.934+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:31:42.933+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:31:43.713+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:31:43.692+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:31:43.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:31:44.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.088 seconds
[2023-11-13T04:32:15.578+0000] {processor.py:157} INFO - Started process (PID=792) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:32:15.580+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:32:15.583+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:32:15.582+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:32:16.298+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:32:16.279+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:32:16.300+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:32:16.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.843 seconds
[2023-11-13T04:32:47.191+0000] {processor.py:157} INFO - Started process (PID=799) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:32:47.193+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:32:47.195+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:32:47.194+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:32:48.031+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:32:48.012+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:32:48.034+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:32:48.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.959 seconds
[2023-11-13T04:33:18.992+0000] {processor.py:157} INFO - Started process (PID=806) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:33:18.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:33:18.997+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:33:18.996+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:33:19.748+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:33:19.729+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:33:19.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:33:19.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.882 seconds
[2023-11-13T04:33:50.575+0000] {processor.py:157} INFO - Started process (PID=813) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:33:50.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:33:50.580+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:33:50.579+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:33:51.357+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:33:51.338+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:33:51.360+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:33:51.476+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.906 seconds
[2023-11-13T04:34:23.028+0000] {processor.py:157} INFO - Started process (PID=820) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:34:23.031+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:34:23.035+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:34:23.034+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:34:23.769+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:34:23.751+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:34:23.772+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:34:23.881+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.860 seconds
[2023-11-13T04:34:54.816+0000] {processor.py:157} INFO - Started process (PID=827) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:34:54.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:34:54.820+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:34:54.819+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:34:55.552+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:34:55.538+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:34:55.554+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:34:55.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.867 seconds
[2023-11-13T04:35:26.198+0000] {processor.py:157} INFO - Started process (PID=834) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:35:26.200+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:35:26.202+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:35:26.201+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:35:27.029+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:35:27.010+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:35:27.032+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:35:27.136+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.942 seconds
[2023-11-13T04:35:58.937+0000] {processor.py:157} INFO - Started process (PID=841) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:35:58.939+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:35:58.941+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:35:58.940+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:35:59.666+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:35:59.652+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:35:59.668+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:35:59.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.894 seconds
[2023-11-13T04:36:30.732+0000] {processor.py:157} INFO - Started process (PID=848) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:36:30.734+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:36:30.736+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:36:30.735+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:36:31.451+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:36:31.431+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:36:31.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:36:32.135+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.408 seconds
[2023-11-13T04:37:02.507+0000] {processor.py:157} INFO - Started process (PID=855) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:02.510+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:37:02.513+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:02.512+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:03.222+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:03.207+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 271, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:37:03.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:03.329+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.826 seconds
[2023-11-13T04:37:21.725+0000] {processor.py:157} INFO - Started process (PID=859) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:21.726+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:37:21.730+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:21.729+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:21.803+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:21.801+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 38
    stt = 0
    ^
IndentationError: unexpected indent
[2023-11-13T04:37:21.804+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:21.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.202 seconds
[2023-11-13T04:37:24.653+0000] {processor.py:157} INFO - Started process (PID=860) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:24.655+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:37:24.657+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:24.657+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:25.561+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:25.546+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 278, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:37:25.564+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:25.681+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.032 seconds
[2023-11-13T04:37:46.171+0000] {processor.py:157} INFO - Started process (PID=865) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:46.173+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:37:46.175+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:46.174+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:47.006+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:46.992+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 278, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:37:47.009+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:47.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.951 seconds
[2023-11-13T04:37:48.460+0000] {processor.py:157} INFO - Started process (PID=867) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:48.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:37:48.465+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:48.464+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:49.328+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:49.313+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 278, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:37:49.331+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:49.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.984 seconds
[2023-11-13T04:37:51.131+0000] {processor.py:157} INFO - Started process (PID=869) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:51.134+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:37:51.136+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:51.135+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:51.833+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:37:51.814+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:37:51.836+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:37:51.952+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.828 seconds
[2023-11-13T04:38:22.639+0000] {processor.py:157} INFO - Started process (PID=876) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:38:22.641+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:38:22.643+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:38:22.642+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:38:23.261+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:38:23.244+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:38:23.264+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:38:23.382+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.748 seconds
[2023-11-13T04:38:54.261+0000] {processor.py:157} INFO - Started process (PID=883) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:38:54.262+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:38:54.265+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:38:54.264+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:38:54.810+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:38:54.789+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:38:54.813+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:38:54.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.674 seconds
[2023-11-13T04:39:25.167+0000] {processor.py:157} INFO - Started process (PID=890) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:39:25.169+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:39:25.171+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:39:25.171+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:39:25.702+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:39:25.686+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:39:25.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:39:25.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.645 seconds
[2023-11-13T04:39:55.980+0000] {processor.py:157} INFO - Started process (PID=897) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:39:55.982+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:39:55.984+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:39:55.984+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:39:56.535+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:39:56.517+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:39:56.537+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:39:56.648+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.672 seconds
[2023-11-13T04:40:27.951+0000] {processor.py:157} INFO - Started process (PID=904) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:40:27.953+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:40:27.956+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:40:27.955+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:40:28.511+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:40:28.492+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:40:28.513+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:40:28.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.680 seconds
[2023-11-13T04:40:59.376+0000] {processor.py:157} INFO - Started process (PID=911) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:40:59.378+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:40:59.380+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:40:59.380+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:40:59.963+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:40:59.948+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:40:59.966+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:00.086+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.714 seconds
[2023-11-13T04:41:10.004+0000] {processor.py:157} INFO - Started process (PID=915) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:10.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:41:10.007+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:41:10.007+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:10.600+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:41:10.581+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 278, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:41:10.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:10.707+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.708 seconds
[2023-11-13T04:41:15.441+0000] {processor.py:157} INFO - Started process (PID=920) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:15.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:41:15.445+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:41:15.444+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:16.076+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:41:16.055+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:41:16.079+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:16.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.764 seconds
[2023-11-13T04:41:47.525+0000] {processor.py:157} INFO - Started process (PID=927) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:47.526+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:41:47.529+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:41:47.528+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:48.053+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:41:48.036+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:41:48.056+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:41:48.166+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.646 seconds
[2023-11-13T04:42:19.574+0000] {processor.py:157} INFO - Started process (PID=934) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:42:19.576+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:42:19.578+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:42:19.577+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:42:20.122+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:42:20.102+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:42:20.124+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:42:20.235+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.666 seconds
[2023-11-13T04:42:51.171+0000] {processor.py:157} INFO - Started process (PID=941) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:42:51.174+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:42:51.177+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:42:51.176+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:42:51.820+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:42:51.801+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:42:51.822+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:42:51.934+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.768 seconds
[2023-11-13T04:43:22.778+0000] {processor.py:157} INFO - Started process (PID=948) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:43:22.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:43:22.782+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:43:22.781+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:43:23.311+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:43:23.294+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:43:23.314+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:43:23.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.643 seconds
[2023-11-13T04:43:54.234+0000] {processor.py:157} INFO - Started process (PID=955) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:43:54.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:43:54.237+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:43:54.237+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:43:54.797+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:43:54.777+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:43:54.800+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:43:54.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.684 seconds
[2023-11-13T04:44:25.829+0000] {processor.py:157} INFO - Started process (PID=962) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:44:25.830+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:44:25.833+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:44:25.832+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:44:26.419+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:44:26.404+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:44:26.422+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:44:26.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.725 seconds
[2023-11-13T04:44:57.392+0000] {processor.py:157} INFO - Started process (PID=969) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:44:57.394+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:44:57.396+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:44:57.396+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:44:57.995+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:44:57.974+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:44:57.998+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:44:58.118+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.730 seconds
[2023-11-13T04:45:29.099+0000] {processor.py:157} INFO - Started process (PID=976) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:29.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:45:29.103+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:45:29.103+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:29.647+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:45:29.629+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 279, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:45:29.649+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:29.768+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.673 seconds
[2023-11-13T04:45:37.619+0000] {processor.py:157} INFO - Started process (PID=978) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:37.621+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:45:37.623+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:45:37.622+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:38.288+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:45:38.271+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 278, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:45:38.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:38.486+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.872 seconds
[2023-11-13T04:45:39.949+0000] {processor.py:157} INFO - Started process (PID=980) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:39.950+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:45:39.952+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:45:39.952+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:40.025+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:45:40.023+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 30
    df.replace(np.nan, '', inplace=True)
    ^
IndentationError: unexpected indent
[2023-11-13T04:45:40.026+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:40.144+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.200 seconds
[2023-11-13T04:45:42.733+0000] {processor.py:157} INFO - Started process (PID=981) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:42.735+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:45:42.737+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:45:42.737+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:43.385+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:45:43.366+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 272, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:45:43.388+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:45:43.494+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.765 seconds
[2023-11-13T04:46:04.664+0000] {processor.py:157} INFO - Started process (PID=988) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:04.666+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:46:04.668+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:46:04.668+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:04.732+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:46:04.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 318
    DeleteOldData >> ExtractTransformdata >> LoadData"""
                                                       ^
SyntaxError: EOF while scanning triple-quoted string literal
[2023-11-13T04:46:04.733+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:04.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.187 seconds
[2023-11-13T04:46:06.864+0000] {processor.py:157} INFO - Started process (PID=989) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:06.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:46:06.869+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:46:06.868+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:07.532+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:46:07.514+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 272, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:46:07.538+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:07.656+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.800 seconds
[2023-11-13T04:46:11.642+0000] {processor.py:157} INFO - Started process (PID=991) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:11.644+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:46:11.646+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:46:11.646+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:12.305+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:46:12.290+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 272, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:46:12.307+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:12.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.789 seconds
[2023-11-13T04:46:43.386+0000] {processor.py:157} INFO - Started process (PID=998) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:43.388+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:46:43.389+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:46:43.389+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:43.878+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:46:43.859+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 272, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:46:43.881+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:46:44.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.621 seconds
[2023-11-13T04:47:15.505+0000] {processor.py:157} INFO - Started process (PID=1005) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:47:15.507+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:47:15.508+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:47:15.508+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:47:16.095+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:47:16.075+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/updateBCTC.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/updateBCTC.py", line 272, in <module>
    LoadBCTC(json_filename)
  File "/opt/airflow/dags/updateBCTC.py", line 28, in LoadBCTC
    df = pd.read_json(pathJsonData, lines=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 917, in _get_data_from_filepath
    raise FileNotFoundError(f"File {filepath_or_buffer} does not exist")
FileNotFoundError: File D:/DataEngineer/airflow/airflow/example/dataBCTC.json does not exist
[2023-11-13T04:47:16.098+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:47:16.377+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.876 seconds
[2023-11-13T04:47:43.437+0000] {processor.py:157} INFO - Started process (PID=1012) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:47:43.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:47:43.440+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:47:43.440+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:47:44.068+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:47:44.265+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:47:44.264+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:47:44.306+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:47:44.306+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:47:44.619+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 1.187 seconds
[2023-11-13T04:48:18.987+0000] {processor.py:157} INFO - Started process (PID=1078) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:48:18.989+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:48:18.991+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:48:18.991+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:48:19.485+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:48:19.546+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:48:19.546+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:48:19.595+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:48:19.595+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:48:19.869+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.886 seconds
[2023-11-13T04:48:51.773+0000] {processor.py:157} INFO - Started process (PID=1085) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:48:51.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:48:51.777+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:48:51.776+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:48:52.289+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:48:52.343+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:48:52.342+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:48:52.389+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:48:52.389+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:48:52.582+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.813 seconds
[2023-11-13T04:49:23.827+0000] {processor.py:157} INFO - Started process (PID=1092) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:49:23.829+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:49:23.831+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:49:23.831+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:49:24.363+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:49:24.418+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:49:24.417+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:49:24.461+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:49:24.461+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:49:24.648+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.825 seconds
[2023-11-13T04:49:55.501+0000] {processor.py:157} INFO - Started process (PID=1099) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:49:55.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:49:55.505+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:49:55.504+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:49:56.098+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:49:56.149+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:49:56.149+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:49:56.193+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:49:56.192+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:49:56.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.889 seconds
[2023-11-13T04:50:27.325+0000] {processor.py:157} INFO - Started process (PID=1106) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:50:27.327+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:50:27.329+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:50:27.328+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:50:27.816+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:50:27.870+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:50:27.869+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:50:27.913+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:50:27.913+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:50:28.103+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.784 seconds
[2023-11-13T04:50:58.358+0000] {processor.py:157} INFO - Started process (PID=1113) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:50:58.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:50:58.361+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:50:58.361+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:50:58.831+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:50:58.889+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:50:58.888+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:50:58.933+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:50:58.932+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:50:59.116+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.763 seconds
[2023-11-13T04:51:29.587+0000] {processor.py:157} INFO - Started process (PID=1120) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:51:29.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:51:29.591+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:51:29.591+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:51:30.095+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:51:30.155+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:51:30.154+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:51:30.197+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:51:30.197+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:51:30.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.791 seconds
[2023-11-13T04:52:00.598+0000] {processor.py:157} INFO - Started process (PID=1127) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:00.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:52:00.601+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:00.601+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:01.231+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:01.289+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:01.288+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:52:01.343+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:01.343+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:52:01.569+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.976 seconds
[2023-11-13T04:52:32.206+0000] {processor.py:157} INFO - Started process (PID=1134) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:32.208+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:52:32.211+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:32.210+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:32.735+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:32.804+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:32.803+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:52:32.853+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:32.853+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:52:33.051+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.849 seconds
[2023-11-13T04:52:59.081+0000] {processor.py:157} INFO - Started process (PID=1138) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:59.083+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:52:59.085+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:59.084+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:59.643+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:52:59.697+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:59.696+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:52:59.743+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:52:59.742+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:52:59.953+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.876 seconds
[2023-11-13T04:53:35.786+0000] {processor.py:157} INFO - Started process (PID=1202) to work on /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:53:35.789+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/updateBCTC.py for tasks to queue
[2023-11-13T04:53:35.791+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:53:35.790+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:53:36.335+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ETL_FinancialReport']) retrieved from /opt/airflow/dags/updateBCTC.py
[2023-11-13T04:53:36.395+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:53:36.394+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-13T04:53:36.443+0000] {logging_mixin.py:154} INFO - [2023-11-13T04:53:36.443+0000] {dag.py:3722} INFO - Setting next_dagrun for ETL_FinancialReport to 2023-12-01T00:00:00+00:00, run_after=2024-01-01T00:00:00+00:00
[2023-11-13T04:53:36.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/updateBCTC.py took 0.868 seconds
